import "../css/main.css";
import testimonials from "./modules/testimonials.js";
import data from "../config.json";
import timer from "./modules/timer.js";
import mode from "./modules/mode.js";
import onOpenForm from "./modules/onOpenForm.js";
import onFormSubmit from "./modules/onFormSubmit.js";
import openMobailMenu from "./modules/mobileMenu.js";
import price from "./modules/price.js";
mode();
timer(data.timerEndDate);
price(data.plans);
testimonials(data.testimonials);
onOpenForm();
onFormSubmit();
openMobailMenu();
