import "../css/main.css";
import { timerEndDate, plans } from "../config.json";
import timer from "./moduls/timer.js";
import mode from "./moduls/mode.js";
import onOpenForm from "./moduls/onOpenForm.js";
import onFormSubmit from "./moduls/onFormSubmit.js";
import openMobailMenu from "./moduls/mobileMenu.js";
import price from "./moduls/price.js";
mode();
timer(timerEndDate);
price(plans);
onOpenForm();
onFormSubmit();
openMobailMenu();
